targets:
  $default:
    builders:
      freezed:
        options:
          # Tells Freezed not to format .freezed.dart files.
          # This can significantly speed up code-generation.
          format: false
          # Disable the generation of copyWith/== for the entire project
          copy_with: false
          equal: false
          # `when` and `map` can be enabled/disabled entirely by setting them to `true`/`false`
          map: true
          # We can also enable/disable specific variants of `when`/`map` by setting them to `true`/`false`:
          when:
            when: true
            maybe_when: true
            when_or_null: false
