name: Analyze

on: workflow_call


jobs:
  analyze:
    name: "Common analyze"
    runs-on: macos-15
    timeout-minutes: 5
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          cache: true

      - run: flutter config --no-cli-animations
      - run: flutter analyze
