name: "Main branch testing"

on:
  push:
    branches:
      - main

jobs:
  Analyze:
    uses: iperon-net/messenger/.github/workflows/_analyze.yaml@main

  Testing:
    needs: [Analyze]
    uses: iperon-net/messenger/.github/workflows/_testing.yaml@main

  AutoTag:
    name: "Auto tag"
    runs-on: macos-15
    timeout-minutes: 5
    needs: [Testing]
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: install cider
        run:
          pub global activate cider
          cider bump breaking --bump-build
