name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  Analyze:
    uses: iperon-net/messenger/.github/workflows/_analyze.yaml@main

  Testing:
    needs: [ Analyze ]
    uses: iperon-net/messenger/.github/workflows/_testing.yaml@main
